# Generated by Django 6.0.3 on 2026-04-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_employee_options_asset_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-assigned_at']},
        ),
    ]
