# Generated by Django 6.0.3 on 2026-04-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='assigned_to',
        ),
    ]
